version: '3.1'
services: 

  postgresdb: 
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secreto

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=correo@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=secreto
    depends_on:
      - "postgresdb"
